"""ReportWriter node: render the final markdown report and persist it to the DB."""
from __future__ import annotations

import logging
import os
from datetime import datetime, timezone
from pathlib import Path

import aiosqlite

from claw.charts import generate_trend_chart
from claw.database import get_db, save_daily_summary
from claw.memory.store import upsert_summary
from claw.pipeline.state import ProductivityState

logger = logging.getLogger(__name__)


def _render_score_bar(score: float, width: int = 20) -> str:
    filled = round(score / 10 * width)
    return "█" * filled + "░" * (width - filled)


async def report_writer(state: ProductivityState) -> dict:
    session_id = state.session_id
    score = state.predicted_score
    bar = _render_score_bar(score)

    goal_rows = ""
    for g in state.goal_details:
        pct = g.get("pct_complete", 0)
        status = "✅" if pct >= 100 else "🔄"
        goal_rows += f"| {status} | {g['title']} | {g.get('current', 0):.0f} / {g.get('target', 0):.0f} | {pct:.0f}% |\n"

    commit_rows = ""
    for e in state.git_events[:10]:
        p = e.get("payload", {})
        if isinstance(p, dict):
            commit_rows += f"- `{p.get('hash','?')}` {p.get('message','')[:80]}\n"

    insight_lines = "\n".join(f"{i+1}. {ins}" for i, ins in enumerate(state.insights))

    report = f"""# Productivity Report — {session_id}

## Score: {score:.1f} / 10  `{bar}`

| Metric | Today |
|--------|-------|
| Focus time | {state.focus_minutes} min |
| Distracted time | {state.distracted_minutes} min |
| Meetings | {state.meeting_minutes} min |
| Commits | {state.commit_count} |
| Goal completion | {state.goal_completion_pct:.0f}% |

## Patterns Detected
{chr(10).join(f"- {p}" for p in state.patterns)}

## Goals
| Status | Goal | Progress | Completion |
|--------|------|----------|------------|
{goal_rows or "| — | No active goals | — | — |"}

## Commits Today
{commit_rows or "_No commits logged today._"}

## Insights & Recommendations
{insight_lines or "_Insufficient data for insights._"}

---
_Generated by Claw at {datetime.now(timezone.utc).strftime('%H:%M UTC')}_
"""

    # Persist to database
    db_path = os.environ.get("DB_PATH", "data/claw.db")
    db = await get_db(db_path)
    try:
        await save_daily_summary(
            db,
            session_id,
            focus_minutes=state.focus_minutes,
            distracted_minutes=state.distracted_minutes,
            meeting_minutes=state.meeting_minutes,
            commit_count=state.commit_count,
            goal_completion_pct=state.goal_completion_pct,
            predicted_score=score,
            report_md=report,
            raw_insights=state.insights,
        )
    finally:
        await db.close()

    # Push to vector store so future sessions can retrieve this as a similar session
    await upsert_summary({
        "session_id": session_id,
        "focus_minutes": state.focus_minutes,
        "distracted_minutes": state.distracted_minutes,
        "commit_count": state.commit_count,
        "goal_completion_pct": state.goal_completion_pct,
        "predicted_score": score,
        "raw_insights": state.insights,
    })

    # Generate trend chart (non-blocking, best-effort)
    chart_path = await generate_trend_chart(session_id)
    if chart_path:
        report += f"\n## Trend Chart\n![Weekly Trends]({chart_path})\n"

    # Write report to file
    output_dir = Path(os.environ.get("REPORT_OUTPUT_DIR", "reports"))
    output_dir.mkdir(parents=True, exist_ok=True)
    report_path = output_dir / f"{session_id}.md"
    report_path.write_text(report, encoding="utf-8")
    logger.info("[report_writer] saved report → %s", report_path)

    return {"report_md": report}
